get_supply/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    re_path(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
    path('auth/', include('authentication.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from main.views import show_products, create_supply, show_json, show_json_by_id, show_xml, show_xml_by_id, register, login_user, logout_user, edit_product, delete_product, add_product_ajax, create_product_flutter
from django.urls import path

app_name = 'main'
urlpatterns = [
    path('', show_products, name='show_products'),
    path('create-supply', create_supply, name='create_supply'),
    path('json/', show_json, name='show_json'),
    path('json/<str:id>', show_json_by_id, name='show_json_by_id'),
    path('xml/', show_xml, name='show_xml'),
    path('xml/<str:id>', show_xml_by_id, name='show_xml_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-product/<uuid:id>', edit_product, name='edit_product'),
    path('delete-product/<uuid:id>', delete_product, name='delete_product'),
    path('add-product-ajax', add_product_ajax, name='add_product_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

main/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User

class Product(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    user_name = models.CharField(max_length=300)
    name = models.CharField(max_length=300)
    price = models.IntegerField()
    description = models.TextField(max_length=300)
    image = models.URLField(max_length=500)

main/forms.py
from typing import Any
from django.forms import ModelForm
from main.models import Product
from django.utils.html import strip_tags

class GetSupplyForm(ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'price', 'description', 'image']
        
    def clean_name(self):
        name = self.cleaned_data["name"]
        return strip_tags(name)
    
    def clean_description(self):
        description = self.cleaned_data["description"]
        return strip_tags(description)

main/views.py
from django.shortcuts import render, redirect, reverse
from main.forms import GetSupplyForm
from main.models import Product
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse
import datetime
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.utils.html import strip_tags
import json

@login_required(login_url='/login')
def show_products(request):
    content = {
        'user_name': request.user.username,
        'name' : 'Rafif Sulaiman Dirvesa',
        'npm' : "2306222771",
        'class' : 'PBP C',
        'last_login' : request.COOKIES['last_login'],
    }
    
    return render(request, 'main.html', content)

def create_supply(request):
    form = GetSupplyForm(request.POST, request.FILES or None)
    if form.is_valid() and request.method == 'POST':
        supply_entry = form.save(commit=False)
        supply_entry.user = request.user
        supply_entry.save()
        return redirect('main:show_products')
    
    context = {"form": form}
    return render(request, 'create_supply.html', context)

def show_xml(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()
    
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('main:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            user = form.get_user()
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_products"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.error(request, 'Username atau password salah!')

    else:
        form = AuthenticationForm(request)
    context = {'form': form}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_product(request, id):
    #get product entry berdasarkan id
    product = Product.objects.get(pk = id)

    # Set product entry sebagai instance dari form
    form = GetSupplyForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_products'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

def delete_product(request, id):
    product = Product.objects.get(pk = id)
    product.delete()
    return HttpResponseRedirect(reverse('main:show_products'))

@csrf_exempt
@require_POST
def add_product_ajax(request):
    form = GetSupplyForm(request.POST, request.FILES or None)
    if form.is_valid():
        supply_entry = form.save(commit=False)
        supply_entry.user = request.user
        supply_entry.save()
        return JsonResponse({'message': 'Product added successfully!'}, status=201)
    else:
        return JsonResponse({'errors': form.errors}, status=400)
    
@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':

        data = json.loads(request.body)
        new_product = Product.objects.create(
            user=request.user,
            name=data['name'],
            price=data['price'],
            description=data['description'],
            image=data['image'],
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/card_info.html
<div class="bg-purple-700 dark:bg-purple-900 rounded-xl overflow-hidden border-2 border-purple-800">
    <div class="p-4 animate-shine">
      <h5 class="text-lg font-semibold text-white">{{ title }}</h5>
      <p class="text-white">{{ value }}</p>
    </div>
</div>

main/templates/card_product.html
<div class="relative break-inside-avoid bg-purple-100 shadow-md rounded-lg mb-6 border-2 border-purple-300 dark:bg-gray-700 max-w-full">
    <!-- Flex container for image and content -->
    <div class="flex flex-wrap items-start p-4 space-x-4 min-w-0">
        <!-- Product image on the left (or top in mobile view) -->
        <div class="flex-shrink-0 w-full sm:w-auto">
            <img src="{{ product_entry.image.url }}" alt="Gambar Produk" class="rounded-xl w-full sm:w-[300px] h-auto">
        </div>

        <!-- Product content on the right (or below image in mobile view) -->
        <div class="flex-grow w-full sm:w-auto mt-4 sm:mt-0 overflow-hidden">
            <h3 class="font-bold text-3xl sm:text-4xl mb-2 break-words">{{ product_entry.name }}</h3>
            <p class="text-gray-600 text-lg sm:text-xl mb-8 dark:text-gray-200 break-words overflow-wrap">{{ product_entry.description }}</p>
            <hr class="border-t-2 border-gray-400 my-4">

            <div class="mt-4">
                <p class="text-xl sm:text-2xl font-bold mt-4 mb-2">Price</p>
                <p class="text-gray-600 text-lg dark:text-gray-200">{{ product_entry.price }}</p>
            </div>
        </div>
    </div>

    <!-- Edit and Delete buttons -->
    <div class="flex justify-end p-4 space-x-2">
        <a href="{% url 'main:edit_product' product_entry.pk %}" class="bg-purple-500 hover:bg-purple-700 text-white rounded-full p-2 transition duration-300 shadow-md">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
            </svg>
        </a>
        <a href="{% url 'main:delete_product' product_entry.pk %}" class="bg-amber-600 hover:bg-amber-700 text-white rounded-full p-2 transition duration-300 shadow-md">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
            </svg>
        </a>
    </div>
</div>

main/templates/create_supply.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block meta %}
<title>Create Product</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<div class="flex flex-col min-h-screen bg-gray-100 dark:bg-gray-900 transition-colors duration-500">
  <div class="container mx-auto px-4 py-8 mt-16 max-w-xl">
    <h1 class="text-3xl font-bold text-center mb-8 text-black dark:text-white">Create New Product</h1>
  
    <div class="bg-white dark:bg-gray-800 shadow-md rounded-lg p-6 form-style">
      <form method="POST" enctype="multipart/form-data" class="space-y-6">
        {% csrf_token %}
        {% for field in form %}
          <div class="flex flex-col">
            <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-gray-700 text-lg dark:text-gray-300">
              {{ field.label }}
            </label>
            <div class="w-full">
              {{ field|add_class:"text-black dark:text-white dark:bg-gray-600" }}
            </div>
            {% if field.help_text %}
              <p class="mt-1 text-sm text-gray-500 dark:text-gray-400">{{ field.help_text }}</p>
            {% endif %}
            {% for error in field.errors %}
              <p class="mt-1 text-sm text-red-600">{{ error }}</p>
            {% endfor %}
          </div>
        {% endfor %}
        <div class="flex justify-center mt-6">
          <button type="submit" class="bg-purple-600 dark:bg-purple-500 text-white font-semibold px-6 py-3 rounded-lg hover:bg-purple-700 dark:hover:bg-purple-600 transition duration-300 ease-in-out w-full">
            Create New Product
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

main/templates/edit_product.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block meta %}
<title>Edit Product</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}
<div class="flex flex-col min-h-screen bg-gray-100 dark:bg-gray-900 transition-colors duration-500">
  <div class="container mx-auto px-4 py-8 mt-16 max-w-xl">
    <h1 class="text-3xl font-bold text-center mb-8 text-black dark:text-white">Edit Product</h1>
  
    <div class="bg-white dark:bg-gray-800 rounded-lg p-6 form-style">
      <form method="POST" class="space-y-6">
          {% csrf_token %}
          {% for field in form %}
              <div class="flex flex-col">
                  <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-gray-700 dark:text-gray-300">
                      {{ field.label }}
                  </label>
                  <div class="w-full">
                      {{ field|add_class:"text-black dark:text-white dark:bg-gray-600"}}
                  </div>
                  {% if field.help_text %}
                      <p class="mt-1 text-sm text-gray-500 dark:text-gray-400">{{ field.help_text }}</p>
                  {% endif %}
                  {% for error in field.errors %}
                      <p class="mt-1 text-sm text-red-600">{{ error }}</p>
                  {% endfor %}
              </div>
          {% endfor %}
          <div class="flex justify-center mt-6">
              <button type="submit" class="bg-indigo-600 dark:bg-indigo-500 text-white font-semibold px-6 py-3 rounded-lg hover:bg-indigo-700 dark:hover:bg-indigo-600 transition duration-300 ease-in-out w-full">
                  Edit Product
              </button>
          </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

main/templates/login.html
{% extends 'base.html' %}
{% include 'navbar.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<div class="login-container flex items-center justify-center h-screen bg-gray-700">
  <div class="login-box bg-white p-10 rounded-lg shadow-md max-w-md w-full">
    <h1 class="getsupply-logo text-center text-4xl mb-10 font-bold text-gray-900">GetSupply</h1>
    <h2 class="login-info text-left text-1l mb-1 font-bold text-red-600">Log In To Your Account</h2>
    
    <form class="space-y-6" method="POST" action="">
      {% csrf_token %}
      <div class="rounded-md shadow-sm">
        <div>
          <input id="username" name="username" type="text" required 
                 class="appearance-none rounded-t-md w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" 
                 placeholder="Username">
        </div>
        <div>
          <input id="password" name="password" type="password" required 
                 class="appearance-none rounded-b-md w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" 
                 placeholder="Password">
        </div>
      </div>

      <div>
        <button type="submit" 
                class="w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-purple-500 hover:bg-purple-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
          Log In
        </button>
      </div>
    </form>

    {% if messages %}
    <div class="mt-4">
      {% for message in messages %}
      {% if message.tags == "success" %}
            <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" role="alert">
                <span class="block sm:inline">{{ message }}</span>
            </div>
        {% elif message.tags == "error" %}
            <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
                <span class="block sm:inline">{{ message }}</span>
            </div>
        {% else %}
            <div class="bg-blue-100 border border-blue-400 text-blue-700 px-4 py-3 rounded relative" role="alert">
                <span class="block sm:inline">{{ message }}</span>
            </div>
        {% endif %}
      {% endfor %}
    </div>
    {% endif %}

    <div class="text-center mt-4">
      <p class="text-sm text-gray-500">
        Don't have an account?
        <a href="{% url 'main:register' %}" class="font-medium text-blue-500 hover:underline">
          Sign up
        </a>
      </p>
    </div>
  </div>
</div>

<style>
  .login-container {
      background-color: #fafafa;
      padding: 40px;
  }

  .login-box {
    border: 1px solid #dbdbdb;
    padding: 50px; /* Adjust padding if necessary */
    max-width: 700px; /* Increase this value to make it wider */
    width: 100%; /* Make it responsive */
    margin-top: 0;
  }

  .login-info {
    font-size: 15px;
  }

  .getsupply-logo {
      {% comment %} font-family: 'Comic Sans MS', cursive; {% endcomment %}
      font-size: 50px;
  }

  .rounded-md input {
      background-color: #fafafa;
      border-color: #dbdbdb;
  }

  .rounded-md input:focus {
      border-color: #a8a8a8;
  }

  .bg-blue-500 {
      background-color: #0095f6;
  }

  .bg-blue-500:hover {
      background-color: #007ac6;
  }

  .text-gray-500 {
      color: #8e8e8e;
  }

  h2 {
    margin-bottom: 10px;
  }
</style>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>GetSupply</title>
<script src="https://cdn.jsdelivr.net/npm/dompurify@3.1.7/dist/purify.min.js"></script>
{% endblock meta %}
{% block content %}
{% include 'navbar.html' %}
<div class="overflow-x-hidden px-4 md:px-8 pb-8 pt-24 min-h-screen bg-gray-100 dark:bg-gray-900 flex flex-col transition-colors duration-500">
  <div class="p-2 mb-6 relative">
    <p class="text-center text-gray-600 dark:text-gray-100 font-bold text-3xl mb-8">Welcome to GetSupply!</p>
    <div class="relative grid grid-cols-1 z-30 md:grid-cols-3 gap-8">
      {% include "card_info.html" with title='Name' value=name %}
      {% include "card_info.html" with title='NPM' value=npm %}
      {% include "card_info.html" with title='Class' value=class %}
    </div>
  </div>
  
  <!-- Kondisi Produk -->
  <section id="products" class="bg-gray-100 dark:bg-gray-900 dark:text-gray-100 transition-colors duration-500">
    <div class="w-full bg-purple-700 dark:bg-purple-800 text-center dark:bg-purple-500 text-white dark:text-gray-200 text-2xl font-bold p-3 rounded-md mb-4">
      Products
    </div>
    <div id="product_cards"></div>
    <div id="crudModal" tabindex="-1" aria-hidden="true" class="hidden fixed inset-0 z-50 w-full flex items-center justify-center bg-gray-800 bg-opacity-50 overflow-x-hidden overflow-y-auto transition-opacity duration-300 ease-out">
      <div id="crudModalContent" class="relative bg-white dark:bg-gray-800 rounded-lg shadow-lg w-5/6 sm:w-3/4 md:w-1/2 lg:w-1/3 mx-4 sm:mx-0 transform scale-95 opacity-0 transition-transform transition-opacity duration-300 ease-out">
        <!-- Modal header -->
        <div class="flex items-center justify-between p-4 border-b dark:border-purple-800 rounded-t">
          <h3 class="text-xl font-semibold text-gray-900 dark:text-gray-300">Add New Product</h3>
          <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center" id="closeModalBtn">
            <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
            </svg>
            <span class="sr-only">Close modal</span>
          </button>
        </div>
        <!-- Modal body -->
        <div class="px-6 py-4 space-y-6 form-style">
          <form id="getSupplyForm" enctype="multipart/form-data">
            <div class="mb-4">
              <label for="name" class="block text-lg font-medium text-gray-700 dark:text-gray-300">Name</label>
              <input type="text" id="name" name="name" class="mt-1 block w-full dark:bg-gray-700 border border-gray-300 dark:border-gray-500 rounded-md p-2 hover:border-purple-700" placeholder="Enter your product's name" required>
            </div>
            <div class="mb-4">
              <label for="price" class="block text-lg font-medium text-gray-700 text-lg dark:text-gray-300">Price</label>
              <input type="number" id="price" name="price" class="mt-1 block w-full border dark:bg-gray-700 border-gray-300 dark:border-gray-500 rounded-md p-2 hover:border-purple-700" required>
            </div>
            <div class="mb-4">
              <label for="description" class="block text-lg font-medium text-gray-700 text-lg dark:text-gray-300">Description</label>
              <textarea id="description" name="description" rows="3" class="mt-1 block w-full dark:bg-gray-700 h-52 resize-none border border-gray-300 dark:border-gray-500 rounded-md p-2 hover:border-purple-700" placeholder="Describe your product" required></textarea>
            </div>
            <div class="mb-4">
              <label for="image" class="block text-lg font-medium text-gray-700 text-lg dark:text-gray-300">Image URL</label>
              <input type="text" id="image" name="image" class="mt-1 block w-full border dark:bg-gray-700 border-gray-300 dark:border-gray-500 rounded-md p-2 hover:border-purple-700" placeholder="Enter the image URL" required>
            </div>
          </form>
        </div>
        <!-- Modal footer -->
        <div class="p-6 border-t border-gray-200 rounded-b dark:border-purple-800">
          <div class="flex flex-col items-end space-y-2">
            <button type="submit" id="submitProduct" form="getSupplyForm" class="bg-purple-700 hover:bg-purple-800 text-white font-bold py-2 px-4 rounded-lg w-full">Add</button>
            <button type="button" class="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded-lg w-full" id="cancelButton">Cancel</button>
          </div>
        </div>
      </div>
    </div>
  </section>  
  
  <!-- Last Login -->
  <div class="flex flex-col h-screen"> <!-- Use h-screen to take full height -->
    <div class="flex-grow"> <!-- This div will expand to fill the space -->
      <!-- Other content here -->
    </div>
    <div class="px-0 mt-6">
      <div class="flex rounded-md items-center bg-purple-600 dark:bg-purple-500 py-2 px-4 w-fit">
        <h1 class="text-white text-center dark:text-gray-200">Last Login: {{last_login}}</h1>
      </div>
    </div>
  </div>  

<script>
  async function getProducts(){
    return fetch("{% url 'main:show_json' %}").then((res) => res.json())
  }

  function addProduct() {
    const form = document.querySelector('#getSupplyForm');
    fetch("{% url 'main:add_product_ajax' %}", {
        method: "POST",
        body: new FormData(form),
    })
    .then(response => response.json())
    .then(data => {
        if (data.errors) {
            // Handle form errors and display them to the user
            displayFormErrors(data.errors);
        } else {
            // Clear the form fields before hiding the modal to ensure it's reset properly
            form.reset(); 
            
            // Refresh products if the submission was successful
            refreshProducts();
            
            // Hide the modal after resetting the form
            hideModal();
        }
    })
    .catch(error => console.error('Error:', error));
}


// Function to display form errors
function displayFormErrors(errors) {
    // Clear any existing error messages
    const errorFields = document.querySelectorAll('.error-message');
    errorFields.forEach((field) => field.remove());

    // Display error messages next to the form fields
    Object.keys(errors).forEach((field) => {
        const errorMessage = errors[field].join(', ');
        const inputField = document.getElementById(field);

        if (inputField) {
            const errorElement = document.createElement('div');
            errorElement.className = 'error-message text-red-500 text-sm mt-1';
            errorElement.innerText = errorMessage;
            inputField.parentElement.appendChild(errorElement);
        }
    });
}

  async function refreshProducts() {
    document.getElementById("product_cards").innerHTML = ""; // Clear existing products
    document.getElementById("product_cards").className = "";
    const productEntries = await getProducts(); // Fetch products
    let htmlString = "";
    let classNameString = "";

    if (productEntries.length === 0) {
        classNameString = "flex flex-col items-center justify-center min-h-[24rem] p-6";
        htmlString = `
            <div class="flex flex-col items-center justify-center min-h-[24rem] p-6">
                <img src="{% static 'gif/laughing.gif' %}" alt="Sad face" class="w-32 h-32 mb-4"/>
                <p class="text-center text-gray-600 mt-4">Data product is empty.</p>
            </div>
        `;
    } else {
        classNameString = "columns-1 sm:columns-2 lg:columns-3 gap-6 space-y-6 w-full";

        productEntries.forEach((item) => {
            const name = DOMPurify.sanitize(item.fields.name);
            const price = DOMPurify.sanitize(item.fields.price);
            const description = DOMPurify.sanitize(item.fields.description);
            const imageUrl = item.fields.image;

            htmlString += `
            <div class="relative break-inside-avoid bg-purple-100 shadow-md rounded-lg mb-6 border-2 border-purple-300 dark:bg-gray-700 max-w-full">
                <!-- Flex container for image and content -->
                <div class="flex flex-wrap items-start p-4 space-x-4 min-w-0">
                    <!-- Product image on the left (or top in mobile view) -->
                    <div class="flex-shrink-0 w-full sm:w-auto">
                        <img src="${imageUrl}" alt="Gambar Produk" class="rounded-xl w-full sm:w-[300px] h-auto">
                    </div>
                    <div class="flex-grow w-full sm:w-auto mt-4 sm:mt-0 overflow-hidden">
                        <h3 class="font-bold text-3xl sm:text-4xl mb-2 break-words">${name}</h3>
                        <p class="text-gray-600 text-lg sm:text-xl mb-8 dark:text-gray-200 break-words overflow-wrap">${description}</p>
                        <hr class="border-t-2 border-gray-400 my-4">
                        <div class="mt-4">
                            <p class="text-xl sm:text-2xl font-bold mt-4 mb-2">Price</p>
                            <p class="text-gray-600 text-lg dark:text-gray-200">Rp. ${price}</p>
                        </div>
                    </div>
                </div>
                <div class="flex justify-end p-4 space-x-2">
                    <a href="/edit-product/${item.pk}" class="bg-purple-500 hover:bg-purple-700 text-white rounded-full p-2 transition duration-300 shadow-md">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                            <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                        </svg>
                    </a>
                    <a href="/delete-product/${item.pk}" class="bg-amber-600 hover:bg-amber-700 text-white rounded-full p-2 transition duration-300 shadow-md">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                            <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
                        </svg>
                    </a>
                </div>
            </div>
            `;
        });
    }
    
    document.getElementById("product_cards").className = classNameString;
    document.getElementById("product_cards").innerHTML = htmlString;
}

const modal = document.getElementById('crudModal');
const modalContent = document.getElementById('crudModalContent');

function showModal() {
  const modal = document.getElementById('crudModal');
  const modalContent = document.getElementById('crudModalContent');
  
  modal.classList.remove('hidden'); 
  setTimeout(() => {
    modalContent.classList.remove('opacity-0', 'scale-95');
    modalContent.classList.add('opacity-100', 'scale-100');
  }, 50); 
}

function hideModal() {
  const modal = document.getElementById('crudModal');
  const modalContent = document.getElementById('crudModalContent');
  
  modalContent.classList.remove('opacity-100', 'scale-100');
  modalContent.classList.add('opacity-0', 'scale-95');
  
  setTimeout(() => {
    modal.classList.add('hidden');
  }, 150); 
}

    document.getElementById("cancelButton").addEventListener("click", hideModal);
    document.getElementById("closeModalBtn").addEventListener("click", hideModal);
    document.getElementById("getSupplyForm").addEventListener("submit", (e) => {
      e.preventDefault();
      addProduct();
    })
refreshProducts();
</script>
{% endblock content %}

.error-message {
  color: #e53e3e; /* Red color for error text */
  font-size: 0.875rem; /* Smaller font size */
  margin-top: 0.25rem; /* Small margin for spacing */
}